### PR TITLE
Fix Habitat removal

### LINKED ISSUE #122: Errors when deleting Habitat resource
When deleting a Habitat, the following errors are displayed:

```
ts=2017-11-08T12:02:17.98051371+01:00 level=info component=controller msg="deleted deployment" name=example-leader-follower-habitat
ts=2017-11-08T12:02:17.983844937+01:00 level=error component=controller msg="deployments.apps \"example-leader-follower-habitat\" not found"
ts=2017-11-08T12:02:17.98428139+01:00 level=error component=controller msg="Habitat could not be synced, requeueing" msg="deployments.apps \"example-leader-follower-habitat\"
 not found"
```

The actual Habitat is removed.

This seems like it could have been introduced in #113.

### PR DESCRIPTION
**Pull request by asymmetric**
This fixes #122.

We were enqueueing Deployments as well as Habitats, but then expecting Habitats in the `enqueue` function.

Additionally, we now perform a type assertion on every handler, for consistency and safety.

### CODE REVIEW

File: pkg/habitat/controller/controller.go [hunk 1]
```diff
@@ -865,10 +897,9 @@ func newConfigMap(ip string) *apiv1.ConfigMap {
 	}
 }
 
-func habitatKeyFromPod(pod *apiv1.Pod) string {
-	hName := pod.Labels[crv1.HabitatNameLabel]
-
-	key := fmt.Sprintf("%s/%s", pod.Namespace, hName)
+func habitatKeyFromResource(r metav1.Object) string {
```
Comment (LiliC) [inline pkg/habitat/controller/controller.go]: We can't get key from all resources, as they are not all labeled, so I feel like the name is a bit misleading.

File: pkg/habitat/controller/controller.go [hunk 2]
```diff
@@ -865,10 +897,9 @@ func newConfigMap(ip string) *apiv1.ConfigMap {
...
+	hName := r.GetLabels()[crv1.HabitatNameLabel]
```
Comment (LiliC) [inline pkg/habitat/controller/controller.go]: Should we check to make sure the label we get is not an empty string? WDYT?

File: pkg/habitat/controller/controller.go [hunk 3]
```diff
@@ -706,10 +738,10 @@ func (hc *HabitatController) newDeployment(h *crv1.Habitat) (*appsv1beta1.Deploy
 	return base, nil
 }
 
-func (hc *HabitatController) enqueue(obj interface{}) {
-	k, err := cache.DeletionHandlingMetaNamespaceKeyFunc(obj)
+func (hc *HabitatController) enqueue(hab *crv1.Habitat) {
+	k, err := cache.DeletionHandlingMetaNamespaceKeyFunc(hab)
 	if err != nil {
-		level.Error(hc.logger).Log("msg", "Object key could not be retrieved", "object", obj)
+		level.Error(hc.logger).Log("msg", "Object key could not be retrieved", "object", hab)
```
Comment (LiliC) [inline pkg/habitat/controller/controller.go]: I guess since we changed it to `Habitat`. We can do something like:
`"msg", "Habitat key could not be retrieved"`

File: pkg/habitat/controller/controller.go (hunk 1 above)
Comment (asymmetric) [reply pkg/habitat/controller/controller.go]: I'll changed it to `..FromLabelResource`

Comment (asymmetric) [reply pkg/habitat/controller/controller.go]: Or [labeled](http://grammarist.com/spelling/label/) :confused:

File: pkg/habitat/controller/controller.go (hunk 3 above)
Comment (LiliC) [reply pkg/habitat/controller/controller.go]: SGTM.

File: pkg/habitat/controller/controller.go (hunk 1 above)
Comment (LiliC) [reply pkg/habitat/controller/controller.go]: haha :D

My two cents: I think American English tends to win in these cases.

File: pkg/habitat/controller/controller.go [hunk 4]
```diff
@@ -855,6 +890,19 @@ func (hc *HabitatController) getHabitatFromPod(pod *apiv1.Pod) (*crv1.Habitat, e
 	return h, nil
 }
 
+// habitatKeyFromLabeledResource returns a Store key for any resource tagged
+// with the `HabitatNameLabel`.
+func habitatKeyFromLabeledResource(r metav1.Object) (string, error) {
+	hName := r.GetLabels()[crv1.HabitatNameLabel]
```
Comment (LiliC) [inline pkg/habitat/controller/controller.go]: We should add an extra check here for `exists`, to prevent panic when a map would access a non existing key.

Comment (asymmetric) [reply pkg/habitat/controller/controller.go]: There is no panic when the key doesn't exist. The zero-value is [returned instead](https://golang.org/doc/effective_go.html#maps):

> An attempt to fetch a map value with a key that is not present in the map will return the zero value for the type of the entries in the map.
